server:
  port: 1688

spring:
  application:
    name: vanguard

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://157.66.26.146:5432/vanguard
    username: postgres
    password: root123

  mail:
    host: smtp.gmail.com
    port: 587
    username: minhnam1810@gmail.com
    password: badl gfvc rbcz zavi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    prefix: classpath:/templates/mail-templates/
    suffix: .html
    mode: HTML

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

jwt:
  signer-key: "gXNsKvdcP2xd0tfC9IxZjr8lbcqUIBhhdgyD5kD1cyXbiZUD4yu6BOZOWlAKss/Z"

cloudinary:
  cloud-name: "dqqqjxnfh"
  api-key: "255558816145194"
  api_secret: "gfcwesLzyJVykvcuJIHctzOOuoU"

#twilio:
#  account-sid: "ACb77b47ab5a2ddad6c33c4ef70d07ba32"
#  auth-token: "a96415ea92d6949a28e06707ec5e0f68"
#  outgoing-sms-number: "+17855725167"

