server:
  port: 1688

spring:
  application:
    name: vanguard

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cqvooglds78s739o47qg-a.singapore-postgres.render.com:5432/vanguard
    username: root
    password: lWbo7awsnpTCnjZU40O0pGhshte8J519

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

logging:
  level:
    org.springframework.boot: DEBUG
    sample.springboot.mybatis: DEBUG
