server:
  port: 1688

spring:
  application:
    name: vanguard

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123

  mail:
    host: smtp.gmail.com
    port: 587
    username: minhnam1810@gmail.com
    password: badl gfvc rbcz zavi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    prefix: classpath:/templates/mail-templates/
    suffix: .html

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

jwt:
  signer-key: "gXNsKvdcP2xd0tfC9IxZjr8lbcqUIBhhdgyD5kD1cyXbiZUD4yu6BOZOWlAKss/Z"
logging:
  level:
    org:
      mybatis: DEBUG
      springframework: DEBUG
    com:
      fpt:
        vanguard: DEBUG

