server:
  port: 1688

spring:
  application:
    name: vanguard

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vanguard
    username: postgres
    password: root123

  mail:
    host: smtp.gmail.com
    port: 587
    username: vanguard.hrm.system@gmail.com
    password: fhno dtts demm jdzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    prefix: classpath:/templates/mail-templates/
    suffix: .html
    mode: HTML

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

jwt:
  signer-key: "gXNsKvdcP2xd0tfC9IxZjr8lbcqUIBhhdgyD5kD1cyXbiZUD4yu6BOZOWlAKss/Z"

cloudinary:
  cloud-name: "dqqqjxnfh"
  api-key: "255558816145194"
  api_secret: "gfcwesLzyJVykvcuJIHctzOOuoU"

