name: Vanguard Application Workflow

on:
  pull_request:
    branches: [main]

env:
  USER_PROJECT: "vanguard"
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/vanguard-hrm-backend"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set short git commit SHA
        id: get_sha
        run: |
          short_sha=$(git rev-parse --short HEAD)
          echo "short_sha=$short_sha" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:sha-${{ env.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_and_push
    steps:
      - name: Execute remote SSH commands as vanguard
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE_TAG: ${{ env.short_sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          DOCKER_IMAGE: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSHKEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DOCKER_IMAGE,IMAGE_TAG,DOCKERHUB_USERNAME,DOCKERHUB_ACCESS_TOKEN
          script: |
            export VANGUARD_APP_NAME=vanguard
            
            sudo -u ${{ env.USER_PROJECT }} bash <<EOF
              set -e
              echo "${DOCKERHUB_ACCESS_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            
              if [ "$(docker ps -aq -f name=$VANGUARD_APP_NAME)" ]; then
                docker stop $VANGUARD_APP_NAME
                docker container rm $VANGUARD_APP_NAME
              fi

              docker run -d -p 8080:8888 \
                --restart unless-stopped \
                --name $VANGUARD_APP_NAME \
                --cpus=1 \
                --memory="512m" \
                -v /etc/vanguard/prod.application.yml:/etc/vanguard/application.yml \
                $DOCKER_IMAGE:sha-$IMAGE_TAG

              docker logout
            EOF
